# Generated by Django 4.2.1 on 2023-05-09 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
